language: go

go:
  - 1.10.x

git:
  depth: 1

services:
  - redis

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
      sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts';
    fi


before_install:
  - source scripts/travis-deps.sh

install:
  - make build-dev-deps
  - go install -v ./...

script:
  - make lint
  - make test
  - goveralls -coverprofile=.coverprofile -service=travis-ci
  - make test-captplanet
