language: go

go:
  - 1.10.x

git:
  depth: 1

services:
  - redis

before_install:
  - source scripts/travis-deps.sh

install:
  - make build-dev-deps
  - go install -v ./...

script:
  - make lint
  - make test
  - goveralls -coverprofile=.coverprofile -service=travis-ci
  - make test-captplanet
